name: Ventilate issues to the right GitHub openbeautyfacts project

on:
  issues:
    types:
      - opened

jobs:
  add-to-projects:
    name: Ventilate issues to the right GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/37 # Add issue to the openbeautyfacts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
